package entity;
// Generated 2017-6-29 16:21:02 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * PdAdmin generated by hbm2java
 */
public class PdAdmin implements java.io.Serializable {

	private Integer id;
	private int fid;
	private String userName;
	private String userPass;
	private Short userSta;
	private Date creatTime;
	private String adminNick;
	private int persion;

	public PdAdmin() {
	}

	public PdAdmin(int fid, String userName, String userPass, Date creatTime, int persion) {
		this.fid = fid;
		this.userName = userName;
		this.userPass = userPass;
		this.creatTime = creatTime;
		this.persion = persion;
	}

	public PdAdmin(int fid, String userName, String userPass, Short userSta, Date creatTime, String adminNick,
			int persion) {
		this.fid = fid;
		this.userName = userName;
		this.userPass = userPass;
		this.userSta = userSta;
		this.creatTime = creatTime;
		this.adminNick = adminNick;
		this.persion = persion;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getFid() {
		return this.fid;
	}

	public void setFid(int fid) {
		this.fid = fid;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

	public Short getUserSta() {
		return this.userSta;
	}

	public void setUserSta(Short userSta) {
		this.userSta = userSta;
	}

	public Date getCreatTime() {
		return this.creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	public String getAdminNick() {
		return this.adminNick;
	}

	public void setAdminNick(String adminNick) {
		this.adminNick = adminNick;
	}

	public int getPersion() {
		return this.persion;
	}

	public void setPersion(int persion) {
		this.persion = persion;
	}

}
