package entity;
// Generated 2017-7-2 14:09:52 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PdAdmin generated by hbm2java
 */
@Entity
@Table(name = "pd_admin", catalog = "stockhh")
public class PdAdmin implements java.io.Serializable {

	private Integer id;
	private int fid;
	private String userName;
	private String userPass;
	private Short userSta;
	private Date creatTime;
	private String adminNick;
	private int persion;

	public PdAdmin() {
	}

	public PdAdmin(int fid, String userName, String userPass, Date creatTime, int persion) {
		this.fid = fid;
		this.userName = userName;
		this.userPass = userPass;
		this.creatTime = creatTime;
		this.persion = persion;
	}

	public PdAdmin(int fid, String userName, String userPass, Short userSta, Date creatTime, String adminNick,
			int persion) {
		this.fid = fid;
		this.userName = userName;
		this.userPass = userPass;
		this.userSta = userSta;
		this.creatTime = creatTime;
		this.adminNick = adminNick;
		this.persion = persion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "fid", nullable = false)
	public int getFid() {
		return this.fid;
	}

	public void setFid(int fid) {
		this.fid = fid;
	}

	@Column(name = "user_name", nullable = false, length = 60)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "user_pass", nullable = false, length = 32)
	public String getUserPass() {
		return this.userPass;
	}

	public void setUserPass(String userPass) {
		this.userPass = userPass;
	}

	@Column(name = "user_sta")
	public Short getUserSta() {
		return this.userSta;
	}

	public void setUserSta(Short userSta) {
		this.userSta = userSta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creat_time", nullable = false, length = 19)
	public Date getCreatTime() {
		return this.creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	@Column(name = "admin_nick", length = 20)
	public String getAdminNick() {
		return this.adminNick;
	}

	public void setAdminNick(String adminNick) {
		this.adminNick = adminNick;
	}

	@Column(name = "persion", nullable = false)
	public int getPersion() {
		return this.persion;
	}

	public void setPersion(int persion) {
		this.persion = persion;
	}

}
