package entity;
// Generated 2017-6-29 16:21:02 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * PdClear generated by hbm2java
 */
public class PdClear implements java.io.Serializable {

	private Integer id;
	private Date creatTime;
	private int memberId;
	private BigDecimal jc;
	private BigDecimal fees;
	private BigDecimal yk;
	private BigDecimal pay;
	private BigDecimal payOut;

	public PdClear() {
	}

	public PdClear(Date creatTime, int memberId, BigDecimal jc, BigDecimal fees, BigDecimal yk, BigDecimal pay,
			BigDecimal payOut) {
		this.creatTime = creatTime;
		this.memberId = memberId;
		this.jc = jc;
		this.fees = fees;
		this.yk = yk;
		this.pay = pay;
		this.payOut = payOut;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getCreatTime() {
		return this.creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public BigDecimal getJc() {
		return this.jc;
	}

	public void setJc(BigDecimal jc) {
		this.jc = jc;
	}

	public BigDecimal getFees() {
		return this.fees;
	}

	public void setFees(BigDecimal fees) {
		this.fees = fees;
	}

	public BigDecimal getYk() {
		return this.yk;
	}

	public void setYk(BigDecimal yk) {
		this.yk = yk;
	}

	public BigDecimal getPay() {
		return this.pay;
	}

	public void setPay(BigDecimal pay) {
		this.pay = pay;
	}

	public BigDecimal getPayOut() {
		return this.payOut;
	}

	public void setPayOut(BigDecimal payOut) {
		this.payOut = payOut;
	}

}
