package entity;
// Generated 2017-7-7 16:21:01 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PdClich generated by hbm2java
 */
@Entity
@Table(name = "pd_clich")
public class PdClich implements java.io.Serializable {

	private Integer id;
	private int entrustId;
	private int memberId;
	private double price;
	private int num;
	private Date creatTime;
	private int closedNum;
	private short pc;
	private double fees;
	private BigDecimal yk;
	private int multiplier;
	private double openprice;
	private int openEntrustId;

	public PdClich() {
	}

	public PdClich(int entrustId, int memberId, double price, int num, Date creatTime, int closedNum, short pc,
			double fees, BigDecimal yk, int multiplier, double openprice, int openEntrustId) {
		this.entrustId = entrustId;
		this.memberId = memberId;
		this.price = price;
		this.num = num;
		this.creatTime = creatTime;
		this.closedNum = closedNum;
		this.pc = pc;
		this.fees = fees;
		this.yk = yk;
		this.multiplier = multiplier;
		this.openprice = openprice;
		this.openEntrustId = openEntrustId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "entrust_id", nullable = false)
	public int getEntrustId() {
		return this.entrustId;
	}

	public void setEntrustId(int entrustId) {
		this.entrustId = entrustId;
	}

	@Column(name = "member_id", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "num", nullable = false)
	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creat_time", nullable = false, length = 19)
	public Date getCreatTime() {
		return this.creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	@Column(name = "closed_num", nullable = false)
	public int getClosedNum() {
		return this.closedNum;
	}

	public void setClosedNum(int closedNum) {
		this.closedNum = closedNum;
	}

	@Column(name = "pc", nullable = false)
	public short getPc() {
		return this.pc;
	}

	public void setPc(short pc) {
		this.pc = pc;
	}

	@Column(name = "fees", nullable = false, precision = 22, scale = 0)
	public double getFees() {
		return this.fees;
	}

	public void setFees(double fees) {
		this.fees = fees;
	}

	@Column(name = "yk", nullable = false, precision = 15)
	public BigDecimal getYk() {
		return this.yk;
	}

	public void setYk(BigDecimal yk) {
		this.yk = yk;
	}

	@Column(name = "multiplier", nullable = false)
	public int getMultiplier() {
		return this.multiplier;
	}

	public void setMultiplier(int multiplier) {
		this.multiplier = multiplier;
	}

	@Column(name = "openprice", nullable = false, precision = 22, scale = 0)
	public double getOpenprice() {
		return this.openprice;
	}

	public void setOpenprice(double openprice) {
		this.openprice = openprice;
	}

	@Column(name = "open_entrust_id", nullable = false)
	public int getOpenEntrustId() {
		return this.openEntrustId;
	}

	public void setOpenEntrustId(int openEntrustId) {
		this.openEntrustId = openEntrustId;
	}

	@Override
	public String toString() {
		return "PdClich [id=" + id + ", entrustId=" + entrustId + ", memberId=" + memberId + ", price=" + price
				+ ", num=" + num + ", creatTime=" + creatTime + ", closedNum=" + closedNum + ", pc=" + pc + ", fees="
				+ fees + ", yk=" + yk + ", multiplier=" + multiplier + ", openprice=" + openprice + ", openEntrustId="
				+ openEntrustId + "]";
	}

}
