package entity;
// Generated 2017-7-2 14:09:52 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PdClear generated by hbm2java
 */
@Entity
@Table(name = "pd_clear", catalog = "stockhh")
public class PdClear implements java.io.Serializable {

	private Integer id;
	private Date creatTime;
	private int memberId;
	private BigDecimal jc;
	private BigDecimal fees;
	private BigDecimal yk;
	private BigDecimal pay;
	private BigDecimal payOut;

	public PdClear() {
	}

	public PdClear(Date creatTime, int memberId, BigDecimal jc, BigDecimal fees, BigDecimal yk, BigDecimal pay,
			BigDecimal payOut) {
		this.creatTime = creatTime;
		this.memberId = memberId;
		this.jc = jc;
		this.fees = fees;
		this.yk = yk;
		this.pay = pay;
		this.payOut = payOut;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "creat_time", nullable = false, length = 10)
	public Date getCreatTime() {
		return this.creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	@Column(name = "member_id", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "jc", nullable = false, precision = 15)
	public BigDecimal getJc() {
		return this.jc;
	}

	public void setJc(BigDecimal jc) {
		this.jc = jc;
	}

	@Column(name = "fees", nullable = false, precision = 15)
	public BigDecimal getFees() {
		return this.fees;
	}

	public void setFees(BigDecimal fees) {
		this.fees = fees;
	}

	@Column(name = "yk", nullable = false, precision = 15)
	public BigDecimal getYk() {
		return this.yk;
	}

	public void setYk(BigDecimal yk) {
		this.yk = yk;
	}

	@Column(name = "pay", nullable = false, precision = 15)
	public BigDecimal getPay() {
		return this.pay;
	}

	public void setPay(BigDecimal pay) {
		this.pay = pay;
	}

	@Column(name = "pay_out", nullable = false, precision = 15)
	public BigDecimal getPayOut() {
		return this.payOut;
	}

	public void setPayOut(BigDecimal payOut) {
		this.payOut = payOut;
	}

}
