package entity;
// Generated 2017-6-29 16:21:02 by Hibernate Tools 5.2.3.Final

/**
 * PdContrct generated by hbm2java
 */
public class PdContrct implements java.io.Serializable {

	private Integer id;
	private String contractNo;
	private double multiplier;
	private String timeSet;
	private String chinaName;
	private String lastTrdeDay;
	private double fees;
	private double ratio;
	private String time1;
	private String time2;
	private short trde;
	private short time1Sta;
	private short time2Sta;
	private short exchange;
	private short del;
	private int marketId;
	private int safeTime;

	public PdContrct() {
	}

	public PdContrct(String contractNo, double multiplier, String timeSet, String chinaName, String lastTrdeDay,
			double fees, double ratio, String time1, String time2, short trde, short time1Sta, short time2Sta,
			short exchange, short del, int marketId, int safeTime) {
		this.contractNo = contractNo;
		this.multiplier = multiplier;
		this.timeSet = timeSet;
		this.chinaName = chinaName;
		this.lastTrdeDay = lastTrdeDay;
		this.fees = fees;
		this.ratio = ratio;
		this.time1 = time1;
		this.time2 = time2;
		this.trde = trde;
		this.time1Sta = time1Sta;
		this.time2Sta = time2Sta;
		this.exchange = exchange;
		this.del = del;
		this.marketId = marketId;
		this.safeTime = safeTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContractNo() {
		return this.contractNo;
	}

	public void setContractNo(String contractNo) {
		this.contractNo = contractNo;
	}

	public double getMultiplier() {
		return this.multiplier;
	}

	public void setMultiplier(double multiplier) {
		this.multiplier = multiplier;
	}

	public String getTimeSet() {
		return this.timeSet;
	}

	public void setTimeSet(String timeSet) {
		this.timeSet = timeSet;
	}

	public String getChinaName() {
		return this.chinaName;
	}

	public void setChinaName(String chinaName) {
		this.chinaName = chinaName;
	}

	public String getLastTrdeDay() {
		return this.lastTrdeDay;
	}

	public void setLastTrdeDay(String lastTrdeDay) {
		this.lastTrdeDay = lastTrdeDay;
	}

	public double getFees() {
		return this.fees;
	}

	public void setFees(double fees) {
		this.fees = fees;
	}

	public double getRatio() {
		return this.ratio;
	}

	public void setRatio(double ratio) {
		this.ratio = ratio;
	}

	public String getTime1() {
		return this.time1;
	}

	public void setTime1(String time1) {
		this.time1 = time1;
	}

	public String getTime2() {
		return this.time2;
	}

	public void setTime2(String time2) {
		this.time2 = time2;
	}

	public short getTrde() {
		return this.trde;
	}

	public void setTrde(short trde) {
		this.trde = trde;
	}

	public short getTime1Sta() {
		return this.time1Sta;
	}

	public void setTime1Sta(short time1Sta) {
		this.time1Sta = time1Sta;
	}

	public short getTime2Sta() {
		return this.time2Sta;
	}

	public void setTime2Sta(short time2Sta) {
		this.time2Sta = time2Sta;
	}

	public short getExchange() {
		return this.exchange;
	}

	public void setExchange(short exchange) {
		this.exchange = exchange;
	}

	public short getDel() {
		return this.del;
	}

	public void setDel(short del) {
		this.del = del;
	}

	public int getMarketId() {
		return this.marketId;
	}

	public void setMarketId(int marketId) {
		this.marketId = marketId;
	}

	public int getSafeTime() {
		return this.safeTime;
	}

	public void setSafeTime(int safeTime) {
		this.safeTime = safeTime;
	}

}
