package entity;
// Generated 2017-6-29 16:21:02 by Hibernate Tools 5.2.3.Final

/**
 * PdCurrency generated by hbm2java
 */
public class PdCurrency implements java.io.Serializable {

	private Integer id;
	private String name;
	private double exchangeUsd;

	public PdCurrency() {
	}

	public PdCurrency(String name, double exchangeUsd) {
		this.name = name;
		this.exchangeUsd = exchangeUsd;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getExchangeUsd() {
		return this.exchangeUsd;
	}

	public void setExchangeUsd(double exchangeUsd) {
		this.exchangeUsd = exchangeUsd;
	}

}
