package entity;
// Generated 2017-7-2 14:09:52 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PdCurrency generated by hbm2java
 */
@Entity
@Table(name = "pd_currency", catalog = "stockhh")
public class PdCurrency implements java.io.Serializable {

	private Integer id;
	private String name;
	private double exchangeUsd;

	public PdCurrency() {
	}

	public PdCurrency(String name, double exchangeUsd) {
		this.name = name;
		this.exchangeUsd = exchangeUsd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "exchange_usd", nullable = false, precision = 22, scale = 0)
	public double getExchangeUsd() {
		return this.exchangeUsd;
	}

	public void setExchangeUsd(double exchangeUsd) {
		this.exchangeUsd = exchangeUsd;
	}

}
