package entity;
// Generated 2017-7-7 16:21:01 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PdEntrust generated by hbm2java
 */
@Entity
@Table(name = "pd_entrust")
public class PdEntrust implements java.io.Serializable {

	private Integer id;
	private int memberId;
	private int contrctId;
	private int num;
	private int clienhNum;
	private double price;
	private short path;
	private short openClose;
	private short sta;
	private Date creatTime;
	private int gitId;
	private Double openprice;
	private int tradetype;
	private int ordertype;

	public PdEntrust() {
	}

	public PdEntrust(int memberId, int contrctId, int num, int clienhNum, double price, short path, short openClose,
			short sta, Date creatTime, int gitId, int tradetype, int ordertype) {
		this.memberId = memberId;
		this.contrctId = contrctId;
		this.num = num;
		this.clienhNum = clienhNum;
		this.price = price;
		this.path = path;
		this.openClose = openClose;
		this.sta = sta;
		this.creatTime = creatTime;
		this.gitId = gitId;
		this.tradetype = tradetype;
		this.ordertype = ordertype;
	}

	public PdEntrust(int memberId, int contrctId, int num, int clienhNum, double price, short path, short openClose,
			short sta, Date creatTime, int gitId, Double openprice, int tradetype, int ordertype) {
		this.memberId = memberId;
		this.contrctId = contrctId;
		this.num = num;
		this.clienhNum = clienhNum;
		this.price = price;
		this.path = path;
		this.openClose = openClose;
		this.sta = sta;
		this.creatTime = creatTime;
		this.gitId = gitId;
		this.openprice = openprice;
		this.tradetype = tradetype;
		this.ordertype = ordertype;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "member_id", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "contrct_id", nullable = false)
	public int getContrctId() {
		return this.contrctId;
	}

	public void setContrctId(int contrctId) {
		this.contrctId = contrctId;
	}

	@Column(name = "num", nullable = false)
	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	@Column(name = "clienh_num", nullable = false)
	public int getClienhNum() {
		return this.clienhNum;
	}

	public void setClienhNum(int clienhNum) {
		this.clienhNum = clienhNum;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "path", nullable = false)
	public short getPath() {
		return this.path;
	}

	public void setPath(short path) {
		this.path = path;
	}

	@Column(name = "open_close", nullable = false)
	public short getOpenClose() {
		return this.openClose;
	}

	public void setOpenClose(short openClose) {
		this.openClose = openClose;
	}

	@Column(name = "sta", nullable = false)
	public short getSta() {
		return this.sta;
	}

	public void setSta(short sta) {
		this.sta = sta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creat_time", nullable = false, length = 19)
	public Date getCreatTime() {
		return this.creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

	@Column(name = "git_id", nullable = false)
	public int getGitId() {
		return this.gitId;
	}

	public void setGitId(int gitId) {
		this.gitId = gitId;
	}

	@Column(name = "openprice", precision = 22, scale = 0)
	public Double getOpenprice() {
		return this.openprice;
	}

	public void setOpenprice(Double openprice) {
		this.openprice = openprice;
	}

	@Column(name = "tradetype", nullable = false)
	public int getTradetype() {
		return this.tradetype;
	}

	public void setTradetype(int tradetype) {
		this.tradetype = tradetype;
	}

	@Column(name = "ordertype", nullable = false)
	public int getOrdertype() {
		return this.ordertype;
	}

	public void setOrdertype(int ordertype) {
		this.ordertype = ordertype;
	}

	@Override
	public String toString() {
		return "PdEntrust [id=" + id + ", memberId=" + memberId + ", contrctId=" + contrctId + ", num=" + num
				+ ", clienhNum=" + clienhNum + ", price=" + price + ", path=" + path + ", openClose=" + openClose
				+ ", sta=" + sta + ", creatTime=" + creatTime + ", gitId=" + gitId + ", openprice=" + openprice
				+ ", tradetype=" + tradetype + ", ordertype=" + ordertype + "]";
	}

}
