package entity;
// Generated 2017-6-29 16:21:02 by Hibernate Tools 5.2.3.Final

/**
 * PdGitprice generated by hbm2java
 */
public class PdGitprice implements java.io.Serializable {

	private Integer id;
	private int gitId;
	private double price;
	private int num;
	private int path;
	private String code;
	private int entrustId;
	private int memberId;
	private int marketId;
	private int auto;

	public PdGitprice() {
	}

	public PdGitprice(int gitId, double price, int num, int path, String code, int entrustId, int memberId,
			int marketId, int auto) {
		this.gitId = gitId;
		this.price = price;
		this.num = num;
		this.path = path;
		this.code = code;
		this.entrustId = entrustId;
		this.memberId = memberId;
		this.marketId = marketId;
		this.auto = auto;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getGitId() {
		return this.gitId;
	}

	public void setGitId(int gitId) {
		this.gitId = gitId;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public int getPath() {
		return this.path;
	}

	public void setPath(int path) {
		this.path = path;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public int getEntrustId() {
		return this.entrustId;
	}

	public void setEntrustId(int entrustId) {
		this.entrustId = entrustId;
	}

	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public int getMarketId() {
		return this.marketId;
	}

	public void setMarketId(int marketId) {
		this.marketId = marketId;
	}

	public int getAuto() {
		return this.auto;
	}

	public void setAuto(int auto) {
		this.auto = auto;
	}

}
