package entity;
// Generated 2017-6-29 16:21:02 by Hibernate Tools 5.2.3.Final

/**
 * PdGit generated by hbm2java
 */
public class PdGit implements java.io.Serializable {

	private Integer id;
	private int memberId;
	private int contrctId;
	private int num;
	private int lockNum;
	private short path;
	private double price;

	public PdGit() {
	}

	public PdGit(int memberId, int contrctId, int num, int lockNum, short path, double price) {
		this.memberId = memberId;
		this.contrctId = contrctId;
		this.num = num;
		this.lockNum = lockNum;
		this.path = path;
		this.price = price;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public int getContrctId() {
		return this.contrctId;
	}

	public void setContrctId(int contrctId) {
		this.contrctId = contrctId;
	}

	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public int getLockNum() {
		return this.lockNum;
	}

	public void setLockNum(int lockNum) {
		this.lockNum = lockNum;
	}

	public short getPath() {
		return this.path;
	}

	public void setPath(short path) {
		this.path = path;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
