package entity;
// Generated 2017-7-2 14:09:52 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PdGit generated by hbm2java
 */
@Entity
@Table(name = "pd_git", catalog = "stockhh")
public class PdGit implements java.io.Serializable {

	private Integer id;
	private int memberId;
	private int contrctId;
	private int num;
	private int lockNum;
	private short path;
	private double price;

	public PdGit() {
	}

	public PdGit(int memberId, int contrctId, int num, int lockNum, short path, double price) {
		this.memberId = memberId;
		this.contrctId = contrctId;
		this.num = num;
		this.lockNum = lockNum;
		this.path = path;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "member_id", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "contrct_id", nullable = false)
	public int getContrctId() {
		return this.contrctId;
	}

	public void setContrctId(int contrctId) {
		this.contrctId = contrctId;
	}

	@Column(name = "num", nullable = false)
	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	@Column(name = "lock_num", nullable = false)
	public int getLockNum() {
		return this.lockNum;
	}

	public void setLockNum(int lockNum) {
		this.lockNum = lockNum;
	}

	@Column(name = "path", nullable = false)
	public short getPath() {
		return this.path;
	}

	public void setPath(short path) {
		this.path = path;
	}

	@Column(name = "price", nullable = false, precision = 20, scale = 4)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
