package entity;
// Generated 2017-7-10 16:52:50 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PdGitprice generated by hbm2java
 */
@Entity
@Table(name = "pd_gitprice")
public class PdGitprice implements java.io.Serializable {

	private Integer id;
	private int gitId;
	private double price;
	private int num;
	private int path;
	private String code;
	private int entrustId;
	private int memberId;
	private int marketId;
	private int auto;

	public PdGitprice() {
	}

	public PdGitprice(int gitId, double price, int num, int path, String code, int entrustId, int memberId,
			int marketId, int auto) {
		this.gitId = gitId;
		this.price = price;
		this.num = num;
		this.path = path;
		this.code = code;
		this.entrustId = entrustId;
		this.memberId = memberId;
		this.marketId = marketId;
		this.auto = auto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "git_id", nullable = false)
	public int getGitId() {
		return this.gitId;
	}

	public void setGitId(int gitId) {
		this.gitId = gitId;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Column(name = "num", nullable = false)
	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	@Column(name = "path", nullable = false)
	public int getPath() {
		return this.path;
	}

	public void setPath(int path) {
		this.path = path;
	}

	@Column(name = "code", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "entrust_id", nullable = false)
	public int getEntrustId() {
		return this.entrustId;
	}

	public void setEntrustId(int entrustId) {
		this.entrustId = entrustId;
	}

	@Column(name = "member_id", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "market_id", nullable = false)
	public int getMarketId() {
		return this.marketId;
	}

	public void setMarketId(int marketId) {
		this.marketId = marketId;
	}

	@Column(name = "Auto", nullable = false)
	public int getAuto() {
		return this.auto;
	}

	public void setAuto(int auto) {
		this.auto = auto;
	}

	@Override
	public String toString() {
		return "PdGitprice [id=" + id + ", gitId=" + gitId + ", price=" + price + ", num=" + num + ", path=" + path
				+ ", code=" + code + ", entrustId=" + entrustId + ", memberId=" + memberId + ", marketId=" + marketId
				+ ", auto=" + auto + "]";
	}

}
