package entity;
// Generated 2017-6-29 16:21:02 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;

/**
 * PdMarket generated by hbm2java
 */
public class PdMarket implements java.io.Serializable {

	private Integer id;
	private String name;
	private String code;
	private double fee;
	private double multiplier;
	private double ratio;
	private short exchange;
	private int safeTime;
	private String time1;
	private String time2;
	private String timeSet;
	private BigDecimal miniprice;

	public PdMarket() {
	}

	public PdMarket(String name, double fee, double multiplier, double ratio, short exchange, int safeTime,
			String time1, String time2, String timeSet, BigDecimal miniprice) {
		this.name = name;
		this.fee = fee;
		this.multiplier = multiplier;
		this.ratio = ratio;
		this.exchange = exchange;
		this.safeTime = safeTime;
		this.time1 = time1;
		this.time2 = time2;
		this.timeSet = timeSet;
		this.miniprice = miniprice;
	}

	public PdMarket(String name, String code, double fee, double multiplier, double ratio, short exchange, int safeTime,
			String time1, String time2, String timeSet, BigDecimal miniprice) {
		this.name = name;
		this.code = code;
		this.fee = fee;
		this.multiplier = multiplier;
		this.ratio = ratio;
		this.exchange = exchange;
		this.safeTime = safeTime;
		this.time1 = time1;
		this.time2 = time2;
		this.timeSet = timeSet;
		this.miniprice = miniprice;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public double getFee() {
		return this.fee;
	}

	public void setFee(double fee) {
		this.fee = fee;
	}

	public double getMultiplier() {
		return this.multiplier;
	}

	public void setMultiplier(double multiplier) {
		this.multiplier = multiplier;
	}

	public double getRatio() {
		return this.ratio;
	}

	public void setRatio(double ratio) {
		this.ratio = ratio;
	}

	public short getExchange() {
		return this.exchange;
	}

	public void setExchange(short exchange) {
		this.exchange = exchange;
	}

	public int getSafeTime() {
		return this.safeTime;
	}

	public void setSafeTime(int safeTime) {
		this.safeTime = safeTime;
	}

	public String getTime1() {
		return this.time1;
	}

	public void setTime1(String time1) {
		this.time1 = time1;
	}

	public String getTime2() {
		return this.time2;
	}

	public void setTime2(String time2) {
		this.time2 = time2;
	}

	public String getTimeSet() {
		return this.timeSet;
	}

	public void setTimeSet(String timeSet) {
		this.timeSet = timeSet;
	}

	public BigDecimal getMiniprice() {
		return this.miniprice;
	}

	public void setMiniprice(BigDecimal miniprice) {
		this.miniprice = miniprice;
	}

}
