package entity;
// Generated 2017-7-2 14:09:52 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PdMarket generated by hbm2java
 */
@Entity
@Table(name = "pd_market", catalog = "stockhh")
public class PdMarket implements java.io.Serializable {

	private Integer id;
	private String name;
	private String code;
	private double fee;
	private double multiplier;
	private double ratio;
	private short exchange;
	private int safeTime;
	private String time1;
	private String time2;
	private String timeSet;
	private BigDecimal miniprice;

	public PdMarket() {
	}

	public PdMarket(String name, double fee, double multiplier, double ratio, short exchange, int safeTime,
			String time1, String time2, String timeSet, BigDecimal miniprice) {
		this.name = name;
		this.fee = fee;
		this.multiplier = multiplier;
		this.ratio = ratio;
		this.exchange = exchange;
		this.safeTime = safeTime;
		this.time1 = time1;
		this.time2 = time2;
		this.timeSet = timeSet;
		this.miniprice = miniprice;
	}

	public PdMarket(String name, String code, double fee, double multiplier, double ratio, short exchange, int safeTime,
			String time1, String time2, String timeSet, BigDecimal miniprice) {
		this.name = name;
		this.code = code;
		this.fee = fee;
		this.multiplier = multiplier;
		this.ratio = ratio;
		this.exchange = exchange;
		this.safeTime = safeTime;
		this.time1 = time1;
		this.time2 = time2;
		this.timeSet = timeSet;
		this.miniprice = miniprice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 10)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", length = 10)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "fee", nullable = false, precision = 22, scale = 0)
	public double getFee() {
		return this.fee;
	}

	public void setFee(double fee) {
		this.fee = fee;
	}

	@Column(name = "multiplier", nullable = false, precision = 22, scale = 0)
	public double getMultiplier() {
		return this.multiplier;
	}

	public void setMultiplier(double multiplier) {
		this.multiplier = multiplier;
	}

	@Column(name = "ratio", nullable = false, precision = 20, scale = 0)
	public double getRatio() {
		return this.ratio;
	}

	public void setRatio(double ratio) {
		this.ratio = ratio;
	}

	@Column(name = "exchange", nullable = false)
	public short getExchange() {
		return this.exchange;
	}

	public void setExchange(short exchange) {
		this.exchange = exchange;
	}

	@Column(name = "safe_time", nullable = false)
	public int getSafeTime() {
		return this.safeTime;
	}

	public void setSafeTime(int safeTime) {
		this.safeTime = safeTime;
	}

	@Column(name = "time1", nullable = false, length = 50)
	public String getTime1() {
		return this.time1;
	}

	public void setTime1(String time1) {
		this.time1 = time1;
	}

	@Column(name = "time2", nullable = false, length = 50)
	public String getTime2() {
		return this.time2;
	}

	public void setTime2(String time2) {
		this.time2 = time2;
	}

	@Column(name = "time_set", nullable = false, length = 300)
	public String getTimeSet() {
		return this.timeSet;
	}

	public void setTimeSet(String timeSet) {
		this.timeSet = timeSet;
	}

	@Column(name = "miniprice", nullable = false, precision = 15, scale = 4)
	public BigDecimal getMiniprice() {
		return this.miniprice;
	}

	public void setMiniprice(BigDecimal miniprice) {
		this.miniprice = miniprice;
	}

}
