package entity;
// Generated 2017-6-29 16:21:02 by Hibernate Tools 5.2.3.Final

import java.util.Date;

/**
 * PdPay generated by hbm2java
 */
public class PdPay implements java.io.Serializable {

	private Integer id;
	private int memberId;
	private double amount;
	private double amountUsd;
	private String orderId;
	private short tp;
	private short sta;
	private short fundsType;
	private short admin;
	private double exchage;
	private Date creatTime;

	public PdPay() {
	}

	public PdPay(int memberId, double amount, double amountUsd, String orderId, short tp, short sta, short fundsType,
			short admin, double exchage, Date creatTime) {
		this.memberId = memberId;
		this.amount = amount;
		this.amountUsd = amountUsd;
		this.orderId = orderId;
		this.tp = tp;
		this.sta = sta;
		this.fundsType = fundsType;
		this.admin = admin;
		this.exchage = exchage;
		this.creatTime = creatTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	public double getAmountUsd() {
		return this.amountUsd;
	}

	public void setAmountUsd(double amountUsd) {
		this.amountUsd = amountUsd;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public short getTp() {
		return this.tp;
	}

	public void setTp(short tp) {
		this.tp = tp;
	}

	public short getSta() {
		return this.sta;
	}

	public void setSta(short sta) {
		this.sta = sta;
	}

	public short getFundsType() {
		return this.fundsType;
	}

	public void setFundsType(short fundsType) {
		this.fundsType = fundsType;
	}

	public short getAdmin() {
		return this.admin;
	}

	public void setAdmin(short admin) {
		this.admin = admin;
	}

	public double getExchage() {
		return this.exchage;
	}

	public void setExchage(double exchage) {
		this.exchage = exchage;
	}

	public Date getCreatTime() {
		return this.creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

}
