package entity;
// Generated 2017-7-2 14:09:52 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PdPayment generated by hbm2java
 */
@Entity
@Table(name = "pd_payment", catalog = "stockhh")
public class PdPayment implements java.io.Serializable {

	private Integer zpyId;
	private String zpyName;
	private String zpyLogo;
	private String zpyContent;
	private String zpyConfig;
	private boolean zpyAvailable;
	private boolean zpyOnline;
	private Integer inputtime;
	private Integer updatetime;

	public PdPayment() {
	}

	public PdPayment(String zpyName, boolean zpyAvailable, boolean zpyOnline) {
		this.zpyName = zpyName;
		this.zpyAvailable = zpyAvailable;
		this.zpyOnline = zpyOnline;
	}

	public PdPayment(String zpyName, String zpyLogo, String zpyContent, String zpyConfig, boolean zpyAvailable,
			boolean zpyOnline, Integer inputtime, Integer updatetime) {
		this.zpyName = zpyName;
		this.zpyLogo = zpyLogo;
		this.zpyContent = zpyContent;
		this.zpyConfig = zpyConfig;
		this.zpyAvailable = zpyAvailable;
		this.zpyOnline = zpyOnline;
		this.inputtime = inputtime;
		this.updatetime = updatetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "zpy_id", unique = true, nullable = false)
	public Integer getZpyId() {
		return this.zpyId;
	}

	public void setZpyId(Integer zpyId) {
		this.zpyId = zpyId;
	}

	@Column(name = "zpy_name", nullable = false, length = 25)
	public String getZpyName() {
		return this.zpyName;
	}

	public void setZpyName(String zpyName) {
		this.zpyName = zpyName;
	}

	@Column(name = "zpy_logo", length = 100)
	public String getZpyLogo() {
		return this.zpyLogo;
	}

	public void setZpyLogo(String zpyLogo) {
		this.zpyLogo = zpyLogo;
	}

	@Column(name = "zpy_content", length = 65535)
	public String getZpyContent() {
		return this.zpyContent;
	}

	public void setZpyContent(String zpyContent) {
		this.zpyContent = zpyContent;
	}

	@Column(name = "zpy_config", length = 65535)
	public String getZpyConfig() {
		return this.zpyConfig;
	}

	public void setZpyConfig(String zpyConfig) {
		this.zpyConfig = zpyConfig;
	}

	@Column(name = "zpy_available", nullable = false)
	public boolean isZpyAvailable() {
		return this.zpyAvailable;
	}

	public void setZpyAvailable(boolean zpyAvailable) {
		this.zpyAvailable = zpyAvailable;
	}

	@Column(name = "zpy_online", nullable = false)
	public boolean isZpyOnline() {
		return this.zpyOnline;
	}

	public void setZpyOnline(boolean zpyOnline) {
		this.zpyOnline = zpyOnline;
	}

	@Column(name = "inputtime")
	public Integer getInputtime() {
		return this.inputtime;
	}

	public void setInputtime(Integer inputtime) {
		this.inputtime = inputtime;
	}

	@Column(name = "updatetime")
	public Integer getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Integer updatetime) {
		this.updatetime = updatetime;
	}

}
