package entity;
// Generated 2017-7-2 14:09:52 by Hibernate Tools 5.2.3.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PdPay generated by hbm2java
 */
@Entity
@Table(name = "pd_pay", catalog = "stockhh")
public class PdPay implements java.io.Serializable {

	private Integer id;
	private int memberId;
	private double amount;
	private double amountUsd;
	private String orderId;
	private short tp;
	private short sta;
	private short fundsType;
	private short admin;
	private double exchage;
	private Date creatTime;

	public PdPay() {
	}

	public PdPay(int memberId, double amount, double amountUsd, String orderId, short tp, short sta, short fundsType,
			short admin, double exchage, Date creatTime) {
		this.memberId = memberId;
		this.amount = amount;
		this.amountUsd = amountUsd;
		this.orderId = orderId;
		this.tp = tp;
		this.sta = sta;
		this.fundsType = fundsType;
		this.admin = admin;
		this.exchage = exchage;
		this.creatTime = creatTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "member_id", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "amount", nullable = false, precision = 22, scale = 0)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Column(name = "amount_usd", nullable = false, precision = 22, scale = 0)
	public double getAmountUsd() {
		return this.amountUsd;
	}

	public void setAmountUsd(double amountUsd) {
		this.amountUsd = amountUsd;
	}

	@Column(name = "order_id", nullable = false, length = 50)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "tp", nullable = false)
	public short getTp() {
		return this.tp;
	}

	public void setTp(short tp) {
		this.tp = tp;
	}

	@Column(name = "sta", nullable = false)
	public short getSta() {
		return this.sta;
	}

	public void setSta(short sta) {
		this.sta = sta;
	}

	@Column(name = "funds_type", nullable = false)
	public short getFundsType() {
		return this.fundsType;
	}

	public void setFundsType(short fundsType) {
		this.fundsType = fundsType;
	}

	@Column(name = "admin", nullable = false)
	public short getAdmin() {
		return this.admin;
	}

	public void setAdmin(short admin) {
		this.admin = admin;
	}

	@Column(name = "exchage", nullable = false, precision = 22, scale = 0)
	public double getExchage() {
		return this.exchage;
	}

	public void setExchage(double exchage) {
		this.exchage = exchage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creat_time", nullable = false, length = 19)
	public Date getCreatTime() {
		return this.creatTime;
	}

	public void setCreatTime(Date creatTime) {
		this.creatTime = creatTime;
	}

}
