package entity;
// Generated 2017-6-29 16:21:02 by Hibernate Tools 5.2.3.Final

/**
 * PdPayment generated by hbm2java
 */
public class PdPayment implements java.io.Serializable {

	private Integer zpyId;
	private String zpyName;
	private String zpyLogo;
	private String zpyContent;
	private String zpyConfig;
	private boolean zpyAvailable;
	private boolean zpyOnline;
	private Integer inputtime;
	private Integer updatetime;

	public PdPayment() {
	}

	public PdPayment(String zpyName, boolean zpyAvailable, boolean zpyOnline) {
		this.zpyName = zpyName;
		this.zpyAvailable = zpyAvailable;
		this.zpyOnline = zpyOnline;
	}

	public PdPayment(String zpyName, String zpyLogo, String zpyContent, String zpyConfig, boolean zpyAvailable,
			boolean zpyOnline, Integer inputtime, Integer updatetime) {
		this.zpyName = zpyName;
		this.zpyLogo = zpyLogo;
		this.zpyContent = zpyContent;
		this.zpyConfig = zpyConfig;
		this.zpyAvailable = zpyAvailable;
		this.zpyOnline = zpyOnline;
		this.inputtime = inputtime;
		this.updatetime = updatetime;
	}

	public Integer getZpyId() {
		return this.zpyId;
	}

	public void setZpyId(Integer zpyId) {
		this.zpyId = zpyId;
	}

	public String getZpyName() {
		return this.zpyName;
	}

	public void setZpyName(String zpyName) {
		this.zpyName = zpyName;
	}

	public String getZpyLogo() {
		return this.zpyLogo;
	}

	public void setZpyLogo(String zpyLogo) {
		this.zpyLogo = zpyLogo;
	}

	public String getZpyContent() {
		return this.zpyContent;
	}

	public void setZpyContent(String zpyContent) {
		this.zpyContent = zpyContent;
	}

	public String getZpyConfig() {
		return this.zpyConfig;
	}

	public void setZpyConfig(String zpyConfig) {
		this.zpyConfig = zpyConfig;
	}

	public boolean isZpyAvailable() {
		return this.zpyAvailable;
	}

	public void setZpyAvailable(boolean zpyAvailable) {
		this.zpyAvailable = zpyAvailable;
	}

	public boolean isZpyOnline() {
		return this.zpyOnline;
	}

	public void setZpyOnline(boolean zpyOnline) {
		this.zpyOnline = zpyOnline;
	}

	public Integer getInputtime() {
		return this.inputtime;
	}

	public void setInputtime(Integer inputtime) {
		this.inputtime = inputtime;
	}

	public Integer getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(Integer updatetime) {
		this.updatetime = updatetime;
	}

}
