package entity;
// Generated 2017-7-2 14:09:52 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PdReceivables generated by hbm2java
 */
@Entity
@Table(name = "pd_receivables", catalog = "stockhh")
public class PdReceivables implements java.io.Serializable {

	private String orderId;
	private String tradeNo;
	private int memberId;
	private String account;
	private float price;
	private int zpyId;
	private boolean state;
	private String note;
	private Integer isDel;
	private int inputtime;

	public PdReceivables() {
	}

	public PdReceivables(String orderId, int memberId, float price, int zpyId, boolean state, int inputtime) {
		this.orderId = orderId;
		this.memberId = memberId;
		this.price = price;
		this.zpyId = zpyId;
		this.state = state;
		this.inputtime = inputtime;
	}

	public PdReceivables(String orderId, String tradeNo, int memberId, String account, float price, int zpyId,
			boolean state, String note, Integer isDel, int inputtime) {
		this.orderId = orderId;
		this.tradeNo = tradeNo;
		this.memberId = memberId;
		this.account = account;
		this.price = price;
		this.zpyId = zpyId;
		this.state = state;
		this.note = note;
		this.isDel = isDel;
		this.inputtime = inputtime;
	}

	@Id

	@Column(name = "order_id", unique = true, nullable = false, length = 20)
	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	@Column(name = "trade_no", length = 50)
	public String getTradeNo() {
		return this.tradeNo;
	}

	public void setTradeNo(String tradeNo) {
		this.tradeNo = tradeNo;
	}

	@Column(name = "member_id", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "account")
	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Column(name = "price", nullable = false, precision = 9)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "zpy_id", nullable = false)
	public int getZpyId() {
		return this.zpyId;
	}

	public void setZpyId(int zpyId) {
		this.zpyId = zpyId;
	}

	@Column(name = "state", nullable = false)
	public boolean isState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Column(name = "isDel")
	public Integer getIsDel() {
		return this.isDel;
	}

	public void setIsDel(Integer isDel) {
		this.isDel = isDel;
	}

	@Column(name = "inputtime", nullable = false)
	public int getInputtime() {
		return this.inputtime;
	}

	public void setInputtime(int inputtime) {
		this.inputtime = inputtime;
	}

}
