package entity;
// Generated 2017-6-29 16:21:02 by Hibernate Tools 5.2.3.Final

/**
 * PdReceivables generated by hbm2java
 */
public class PdReceivables implements java.io.Serializable {

	private String orderId;
	private String tradeNo;
	private int memberId;
	private String account;
	private float price;
	private int zpyId;
	private boolean state;
	private String note;
	private Integer isDel;
	private int inputtime;

	public PdReceivables() {
	}

	public PdReceivables(String orderId, int memberId, float price, int zpyId, boolean state, int inputtime) {
		this.orderId = orderId;
		this.memberId = memberId;
		this.price = price;
		this.zpyId = zpyId;
		this.state = state;
		this.inputtime = inputtime;
	}

	public PdReceivables(String orderId, String tradeNo, int memberId, String account, float price, int zpyId,
			boolean state, String note, Integer isDel, int inputtime) {
		this.orderId = orderId;
		this.tradeNo = tradeNo;
		this.memberId = memberId;
		this.account = account;
		this.price = price;
		this.zpyId = zpyId;
		this.state = state;
		this.note = note;
		this.isDel = isDel;
		this.inputtime = inputtime;
	}

	public String getOrderId() {
		return this.orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	public String getTradeNo() {
		return this.tradeNo;
	}

	public void setTradeNo(String tradeNo) {
		this.tradeNo = tradeNo;
	}

	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	public int getZpyId() {
		return this.zpyId;
	}

	public void setZpyId(int zpyId) {
		this.zpyId = zpyId;
	}

	public boolean isState() {
		return this.state;
	}

	public void setState(boolean state) {
		this.state = state;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Integer getIsDel() {
		return this.isDel;
	}

	public void setIsDel(Integer isDel) {
		this.isDel = isDel;
	}

	public int getInputtime() {
		return this.inputtime;
	}

	public void setInputtime(int inputtime) {
		this.inputtime = inputtime;
	}

}
