package entity;
// Generated 2017-6-29 16:21:02 by Hibernate Tools 5.2.3.Final

/**
 * PdSetting generated by hbm2java
 */
public class PdSetting implements java.io.Serializable {

	private Integer zstId;
	private boolean zklType;
	private String zklTitle;
	private String zklVariable;
	private String zklValued;

	public PdSetting() {
	}

	public PdSetting(boolean zklType, String zklVariable, String zklValued) {
		this.zklType = zklType;
		this.zklVariable = zklVariable;
		this.zklValued = zklValued;
	}

	public PdSetting(boolean zklType, String zklTitle, String zklVariable, String zklValued) {
		this.zklType = zklType;
		this.zklTitle = zklTitle;
		this.zklVariable = zklVariable;
		this.zklValued = zklValued;
	}

	public Integer getZstId() {
		return this.zstId;
	}

	public void setZstId(Integer zstId) {
		this.zstId = zstId;
	}

	public boolean isZklType() {
		return this.zklType;
	}

	public void setZklType(boolean zklType) {
		this.zklType = zklType;
	}

	public String getZklTitle() {
		return this.zklTitle;
	}

	public void setZklTitle(String zklTitle) {
		this.zklTitle = zklTitle;
	}

	public String getZklVariable() {
		return this.zklVariable;
	}

	public void setZklVariable(String zklVariable) {
		this.zklVariable = zklVariable;
	}

	public String getZklValued() {
		return this.zklValued;
	}

	public void setZklValued(String zklValued) {
		this.zklValued = zklValued;
	}

}
