package entity;
// Generated 2017-7-2 14:09:52 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PdSys generated by hbm2java
 */
@Entity
@Table(name = "pd_sys", catalog = "stockhh")
public class PdSys implements java.io.Serializable {

	private Integer id;
	private int pay;
	private int trde;
	private String payUrl;

	public PdSys() {
	}

	public PdSys(int pay, int trde) {
		this.pay = pay;
		this.trde = trde;
	}

	public PdSys(int pay, int trde, String payUrl) {
		this.pay = pay;
		this.trde = trde;
		this.payUrl = payUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "pay", nullable = false)
	public int getPay() {
		return this.pay;
	}

	public void setPay(int pay) {
		this.pay = pay;
	}

	@Column(name = "trde", nullable = false)
	public int getTrde() {
		return this.trde;
	}

	public void setTrde(int trde) {
		this.trde = trde;
	}

	@Column(name = "pay_url", length = 400)
	public String getPayUrl() {
		return this.payUrl;
	}

	public void setPayUrl(String payUrl) {
		this.payUrl = payUrl;
	}

}
