package entity;
// Generated 2017-6-29 16:21:02 by Hibernate Tools 5.2.3.Final

/**
 * PdSys generated by hbm2java
 */
public class PdSys implements java.io.Serializable {

	private Integer id;
	private int pay;
	private int trde;
	private String payUrl;

	public PdSys() {
	}

	public PdSys(int pay, int trde) {
		this.pay = pay;
		this.trde = trde;
	}

	public PdSys(int pay, int trde, String payUrl) {
		this.pay = pay;
		this.trde = trde;
		this.payUrl = payUrl;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPay() {
		return this.pay;
	}

	public void setPay(int pay) {
		this.pay = pay;
	}

	public int getTrde() {
		return this.trde;
	}

	public void setTrde(int trde) {
		this.trde = trde;
	}

	public String getPayUrl() {
		return this.payUrl;
	}

	public void setPayUrl(String payUrl) {
		this.payUrl = payUrl;
	}

}
