package entity;
// Generated 2017-6-29 16:21:02 by Hibernate Tools 5.2.3.Final

/**
 * PdUserSet generated by hbm2java
 */
public class PdUserSet implements java.io.Serializable {

	private Integer id;
	private short type;
	private int marketId;
	private int memberId;
	private String value;

	public PdUserSet() {
	}

	public PdUserSet(short type, int marketId, int memberId, String value) {
		this.type = type;
		this.marketId = marketId;
		this.memberId = memberId;
		this.value = value;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public short getType() {
		return this.type;
	}

	public void setType(short type) {
		this.type = type;
	}

	public int getMarketId() {
		return this.marketId;
	}

	public void setMarketId(int marketId) {
		this.marketId = marketId;
	}

	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
