package entity;
// Generated 2017-7-2 14:09:52 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PdUserSet generated by hbm2java
 */
@Entity
@Table(name = "pd_user_set", catalog = "stockhh")
public class PdUserSet implements java.io.Serializable {

	private Integer id;
	private short type;
	private int marketId;
	private int memberId;
	private String value;

	public PdUserSet() {
	}

	public PdUserSet(short type, int marketId, int memberId, String value) {
		this.type = type;
		this.marketId = marketId;
		this.memberId = memberId;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false)
	public short getType() {
		return this.type;
	}

	public void setType(short type) {
		this.type = type;
	}

	@Column(name = "market_id", nullable = false)
	public int getMarketId() {
		return this.marketId;
	}

	public void setMarketId(int marketId) {
		this.marketId = marketId;
	}

	@Column(name = "member_id", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "value", nullable = false, length = 20)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
