package entity;
// Generated 2017-7-2 14:09:52 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PdUserFee generated by hbm2java
 */
@Entity
@Table(name = "pd_user_fee", catalog = "stockhh")
public class PdUserFee implements java.io.Serializable {

	private Integer id;
	private int marketId;
	private int memberId;
	private double fees;

	public PdUserFee() {
	}

	public PdUserFee(int marketId, int memberId, double fees) {
		this.marketId = marketId;
		this.memberId = memberId;
		this.fees = fees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "market_id", nullable = false)
	public int getMarketId() {
		return this.marketId;
	}

	public void setMarketId(int marketId) {
		this.marketId = marketId;
	}

	@Column(name = "member_id", nullable = false)
	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	@Column(name = "fees", nullable = false, precision = 22, scale = 0)
	public double getFees() {
		return this.fees;
	}

	public void setFees(double fees) {
		this.fees = fees;
	}

}
