package entity;
// Generated 2017-6-29 16:21:02 by Hibernate Tools 5.2.3.Final

/**
 * PdUserFee generated by hbm2java
 */
public class PdUserFee implements java.io.Serializable {

	private Integer id;
	private int marketId;
	private int memberId;
	private double fees;

	public PdUserFee() {
	}

	public PdUserFee(int marketId, int memberId, double fees) {
		this.marketId = marketId;
		this.memberId = memberId;
		this.fees = fees;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getMarketId() {
		return this.marketId;
	}

	public void setMarketId(int marketId) {
		this.marketId = marketId;
	}

	public int getMemberId() {
		return this.memberId;
	}

	public void setMemberId(int memberId) {
		this.memberId = memberId;
	}

	public double getFees() {
		return this.fees;
	}

	public void setFees(double fees) {
		this.fees = fees;
	}

}
